// Illustrator export (generated by protein2vector.py - placeholders replaced).
// Opens each SVG, builds one layer per group, saves a native .ai
// (PDF-compatible, layers preserved).
var OUTDIR = "{{OUTDIR}}";
var report = "";
function log(s) { report += s + "\n"; }

// suppress modal alerts (e.g. the SVG-import "clipping will be lost"
// warning): an unattended modal dialog blocks the COM call forever
app.userInteractionLevel = UserInteractionLevel.DONTDISPLAYALERTS;

var JOBS = {{JOBS}};

var opts = new IllustratorSaveOptions();
opts.pdfCompatible = true;

for (var j = 0; j < JOBS.length; j++) {
    var svgPath = JOBS[j][0], outPath = JOBS[j][1], tag = JOBS[j][2];
    var names = JOBS[j][3];

    var doc = app.open(new File(svgPath));
    log("[" + tag + "] opened; layers=" + doc.layers.length +
        " groupItems=" + doc.groupItems.length);

    // one top-level layer per group (created bottom-up; add() stacks on top)
    for (var n = 0; n < names.length; n++) {
        var match = names[n].replace(/_/g, " ");   // AI converts _ to space on import
        var L = null;
        for (var i = 0; i < doc.layers.length; i++)
            if (doc.layers[i].name == names[n] || doc.layers[i].name == match) {
                L = doc.layers[i]; break; }
        if (L == null) { L = doc.layers.add(); L.name = names[n]; }
        for (var g = doc.groupItems.length - 1; g >= 0; g--) {
            var gi = doc.groupItems[g];
            if ((gi.name == names[n] || gi.name == match) && gi.parent &&
                gi.parent.typename == "Layer" && gi.parent != L)
                gi.move(L, ElementPlacement.PLACEATEND);
        }
    }
    // drop residual empty layers
    for (var i = doc.layers.length - 1; i >= 0; i--) {
        var Lx = doc.layers[i];
        var empty = (Lx.groupItems.length == 0 && Lx.pathItems.length == 0 &&
                     Lx.compoundPathItems.length == 0 && Lx.textFrames.length == 0 &&
                     Lx.rasterItems.length == 0 && Lx.placedItems.length == 0);
        if (empty && doc.layers.length > 1) { log("[" + tag + "] remove empty " + Lx.name); Lx.remove(); }
    }

    doc.saveAs(new File(outPath), opts);
    log("[" + tag + "] saved " + outPath);
    doc.close(SaveOptions.DONOTSAVECHANGES);
}

var f = new File("{{REPORT}}");
f.encoding = "UTF-8"; f.open("w"); f.write(report); f.close();

// close the whole application, not just the documents: unattended
// Illustrator processes otherwise linger and block later COM runs
app.quit();
